&ACCESS RVP
&REL 1
DEF  AppFeedbackSPS ( )
; **************************************
; * Package:     TeslaCore             *
; * Release      V5.0.0                *
; * File:        AppFeedbackSPS.sub    *
; * Date:        04.2019               *
; * GUI Version: > = V8.3              *
; **************************************
;FOLD Details
;FOLD Declaration
;ENDFOLD (Declaration)
;FOLD Implementation
LOOP
;FOLD Application Feedback
;ENDFOLD (Application Feedback)
ENDLOOP
;ENDFOLD (Implementation)
;ENDFOLD (Details)
END ; (AppFeedbackSPS)
